# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 143cafdcbcf4050136816d73c9b90db5389fde4ba8d5cd8d3b54fff36ac75d6ebf9fd55b8332f5026b9a005b6363165ec9650dc989606ba98b4dac03f5771014

test:
  secret_key_base: 1175319c87ef58130098a67af858660d87fd761fa32597e05a2fbdc19ebed89c5e8796fc6f1f7509f0e393243e49d4ec4c6a1ed6bc6a33609ce3b3c12d7f9c0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 149bba1bcbff6586ea67c12b7e5eae2c259728bc # some random phrase <%= ENV["SECRET_KEY_BASE"] %>
